CREATE TABLE IF NOT EXISTS `kyc_verifications` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `role` varchar(50) NOT NULL,
  `status` enum('draft','pending','verified','rejected') NOT NULL DEFAULT 'draft',

  `full_name` varchar(255) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `id_document_type` varchar(50) DEFAULT NULL,
  `id_document_number` varchar(100) DEFAULT NULL,
  `permanent_address` text DEFAULT NULL,
  `current_address` text DEFAULT NULL,

  `business_name` varchar(255) DEFAULT NULL,
  `business_type` varchar(100) DEFAULT NULL,
  `registration_number` varchar(100) DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `pan_vat` varchar(50) DEFAULT NULL,
  `industry` varchar(100) DEFAULT NULL,
  `business_address` text DEFAULT NULL,
  `business_url` varchar(255) DEFAULT NULL,
  `monthly_sales` decimal(15,2) DEFAULT NULL,
  `intent` varchar(100) DEFAULT NULL,
  `business_description` text DEFAULT NULL,

  `investor_type` varchar(100) DEFAULT NULL,
  `investment_ticket_min` decimal(15,2) DEFAULT NULL,
  `investment_ticket_max` decimal(15,2) DEFAULT NULL,
  `preferred_sectors` text DEFAULT NULL,
  `total_capital_deployed` decimal(15,2) DEFAULT NULL,
  `past_investments` int(11) DEFAULT NULL,

  `id_front_path` varchar(255) DEFAULT NULL,
  `id_back_path` varchar(255) DEFAULT NULL,
  `registration_cert_path` varchar(255) DEFAULT NULL,
  `pan_cert_path` varchar(255) DEFAULT NULL,
  `financial_proof_path` varchar(255) DEFAULT NULL,
  `business_photo_path` varchar(255) DEFAULT NULL,
  `profile_photo_path` varchar(255) DEFAULT NULL,

  `risk_score` int(11) NOT NULL DEFAULT 0,
  `rejection_reason` text DEFAULT NULL,
  `reviewed_by` bigint(20) UNSIGNED DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),

  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `reviewed_by` (`reviewed_by`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
